set(OPENSOURCE_COMPONENT_NAME "hseceasy")
set(OPENSOURCE_COMPONENT_DIR "${THIRD_PARTY_SRC_DIR}/${OPENSOURCE_COMPONENT_NAME}")
set(OPENSOURCE_COMPONENT_INSTALL_DIR "${THIRD_PARTY_OUTPUT_DIR}/${OPENSOURCE_COMPONENT_NAME}")

if(EXISTS "${OPENSOURCE_COMPONENT_INSTALL_DIR}")
    message(STATUS "${OPENSOURCE_COMPONENT_NAME} already installed, skipping download.")
    return()
endif()

if(NOT EXISTS "${OPENSOURCE_COMPONENT_DIR}/lib")  # 修改为组件自己的判断逻辑
    message(STATUS "${OPENSOURCE_COMPONENT_NAME} not found, downloading and extracting...")
    if(EXISTS "${OPENSOURCE_COMPONENT_DIR}")
        message(STATUS "Clean the dir: ${OPENSOURCE_COMPONENT_DIR}")
        file(REMOVE_RECURSE "${OPENSOURCE_COMPONENT_DIR}")
    endif()
    download_open_source(${OPENSOURCE_COMPONENT_NAME})
endif()

file(COPY ${OPENSOURCE_COMPONENT_DIR} DESTINATION ${THIRD_PARTY_OUTPUT_DIR})