set(NLOHMANN_DIR "${THIRD_PARTY_SRC_DIR}/nlohmannJson")
set(NLOHMANN_OUTPUT_DIR "${THIRD_PARTY_OUTPUT_DIR}/nlohmannJson")

if(EXISTS ${NLOHMANN_OUTPUT_DIR})
    message(STATUS "nlohmannJson already exists, skipping download and extract.")
    return()
endif()

if(NOT EXISTS "${NLOHMANN_DIR}/include")
    message(STATUS "nlohmannJson not found, downloading and extracting...")
    if(EXISTS "${NLOHMANN_DIR}")
        file(REMOVE_RECURSE "${NLOHMANN_DIR}")
    endif()
    download_open_source(nlohmannJson)
else()
    message(STATUS "nlohmannJson already exists, skipping download and extract.")
endif()

file(COPY ${NLOHMANN_DIR}/include DESTINATION ${NLOHMANN_OUTPUT_DIR})
message(("download nlohmannJson successful!"))
